[versions]
agp = "8.13.1"
api = "13.1.5"
boringssl = "20250114"
gson = "2.13.2"
hiddenapibypass = "6.1"
ksp = "2.1.21-2.0.2"
kotlin = "2.2.10"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
library = "1.2.1"
material = "1.13.0"
sdpAndroid = "1.1.1"
recyclerview = "1.4.0"
toml4j = "0.7.2"
volley = "1.2.1"
webkit = "1.14.0"
constraintlayout = "2.2.1"
workRuntime = "2.10.3"
zip4j = "2.11.5"
activityCompose = "1.10.1"
composeBom = "2025.08.01"
parcelablelist = "2.0.1"
navigationCompose = "2.9.3"
coil-compose = "2.7.0"
appiconloader-coil = "1.5.0"
mmrl = "v33890"
hidden-api = "4.4.0"
refine = "4.4.0"
compose-destination = "2.2.0"
foundation = "1.9.0"
markdown = "4.6.2"
annotationJvm = "1.9.1"
lifecycleLivedataCoreKtx = "2.10.0"
compatibility = "2.0.0"
libcxx = "27.0.12077973"
lifecycleLivedataKtx = "2.9.0"
annotation = "1.9.1"
coreKtxRikka = "1.4.1"
bcpkix = "1.80"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
boringssl = { module = "io.github.vvb2060.ndk:boringssl", version.ref = "boringssl" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
ansi-library = { module = "com.github.Fox2Code.AndroidANSI:library", version.ref = "library" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
toml4j = { module = "com.moandjiezana.toml:toml4j", version.ref = "toml4j" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }

dev-rikka-rikkax-parcelablelist = { module = "dev.rikka.rikkax.parcelablelist:parcelablelist", version.ref = "parcelablelist" }

compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

compose-destinations-core = { group = "io.github.raamcosta.compose-destinations", name = "core", version.ref = "compose-destination" }
compose-destinations-ksp = { group = "io.github.raamcosta.compose-destinations", name = "ksp", version.ref = "compose-destination" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose" }
appiconloader-coil = { group = "me.zhanghai.android.appiconloader", name = "appiconloader-coil", version.ref = "appiconloader-coil" }
mmrl-ui = { group = "com.github.MMRLApp.MMRL", name = "ui", version.ref = "mmrl" }

hidden-compat = { group = "dev.rikka.hidden", name = "compat", version.ref = "hidden-api" }
hidden-stub = { group = "dev.rikka.hidden", name = "stub", version.ref = "hidden-api" }

refine-runtime = { group = "dev.rikka.tools.refine", name = "runtime", version.ref = "refine" }
refine-annotation = { group = "dev.rikka.tools.refine", name = "annotation", version.ref = "refine" }
refine-annotation-processor = { group = "dev.rikka.tools.refine", name = "annotation-processor", version.ref = "refine" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }

markdown = { group = "io.noties.markwon", name = "core", version.ref = "markdown" }
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }
androidx-lifecycle-livedata-core-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-core-ktx", version.ref = "lifecycleLivedataCoreKtx" }
dev-rikka-rikkax-compatibility = { module = "dev.rikka.rikkax.compatibility:compatibility", version.ref = "compatibility" }
org-lsposed-libcxx = { module = "org.lsposed.libcxx:libcxx", version.ref = "libcxx" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
ansi-library-ktx = { module = "com.github.Fox2Code.AndroidANSI:library-ktx", version.ref = "library" }
dev-rikka-rikkax-core-ktx = { module = "dev.rikka.rikkax.core:core-ktx", version.ref = "coreKtxRikka" }
bcpkix-jdk18on = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bcpkix" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
tools-refine = { id = "dev.rikka.tools.refine", version.ref = "refine" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

